# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f43658e5238e268627fa745c52d372fa4770c0325f2b699ad851489851aa0d5bd3e215883c53df8b3a36707d831c863c152afadfe23caaad19bd3feb94e810d

test:
  secret_key_base: fc2a7c8b56a4a74efb6bf123f861c21a9eec2d7633ce0ba3e52f2e9fbdb55267d3d836ae6b10df93fd9eb9bfb288d81144c62288639604122802e3d4f171ad73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
